"""
scratch/generate_golden_record_model.py
Reads schema.py SCHEMA_DATA and writes app/models/golden_record.py —
a Pydantic BaseModel with all 163 parameters as Optional[str] fields.
Run from the project root:
    python scratch/generate_golden_record_model.py
"""
import os, re, sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from schema import SCHEMA_DATA

OUT = os.path.join(os.path.dirname(__file__), "..", "app", "models", "golden_record.py")


def to_field_name(s: str) -> str:
    """Convert a parameter name like 'CAC:LTV Ratio' → 'cac_ltv_ratio'."""
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "_", s)
    s = re.sub(r"_+", "_", s)
    return s.strip("_")


# Build lines
lines = [
    '"""',
    "app/models/golden_record.py — AUTO-GENERATED by scratch/generate_golden_record_model.py",
    "Contains all 163 golden-record parameters as a Pydantic model.",
    "Swagger UI will enumerate every field in the /docs schema explorer.",
    '"""',
    "from __future__ import annotations",
    "from typing import Optional",
    "from pydantic import BaseModel, Field",
    "",
    "",
    "class GoldenRecord(BaseModel):",
    '    """All 163 research parameters for a company golden record."""',
    "",
]

seen_field_names: dict[str, int] = {}

for item in SCHEMA_DATA:
    param   = item["parameter"]
    desc    = item["description"]
    cat     = item["category"]
    ac      = item["ac"]
    id_num  = item["id"]

    field_name = to_field_name(param)

    # Deduplicate clashing Python names
    if field_name in seen_field_names:
        seen_field_names[field_name] += 1
        field_name = f"{field_name}_{seen_field_names[field_name]}"
    else:
        seen_field_names[field_name] = 0

    # Escape quotes in alias / description
    alias_safe = param.replace('"', '\\"')
    desc_safe  = desc.replace('"', '\\"')

    lines.append(
        f'    {field_name}: Optional[str] = Field('
        f'None, alias="{alias_safe}", '
        f'description="[{id_num}] [{cat}] [{ac}] {desc_safe}")'
    )

lines += [
    "",
    "    model_config = {",
    '        "populate_by_name": True,',
    '        "json_schema_extra": {',
    '            "description": "Golden record containing all 163 company research parameters"',
    "        },",
    "    }",
    "",
]

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Written {len(SCHEMA_DATA)} fields -> {OUT}")

# Verify it's importable
import importlib.util
spec = importlib.util.spec_from_file_location("golden_record", OUT)
mod  = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
gr = mod.GoldenRecord
fields = list(gr.model_fields.keys())
print(f"Verified: {len(fields)} fields. First={fields[0]}  Last={fields[-1]}")
