"""
Reads schema.tsv and writes a fully self-contained schema.py with
all 163 parameters hardcoded — no runtime file I/O needed.
Run once from the project root:
    python scratch/generate_schema_py.py
"""
import os
import re

TSV_PATH  = os.path.join(os.path.dirname(__file__), "..", "schema.tsv")
OUT_PATH  = os.path.join(os.path.dirname(__file__), "..", "schema.py")

rows = []
with open(TSV_PATH, encoding="utf-8") as f:
    for line in f:
        line = line.rstrip("\n")
        if not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) >= 8:
            rows.append({
                "id":           parts[0].strip(),
                "category":     parts[1].strip(),
                "description":  parts[2].strip(),
                "parameter":    parts[3].strip(),
                "content_type": parts[4].strip(),
                "min":          parts[5].strip(),
                "max":          parts[6].strip(),
                "ac":           parts[7].strip(),
            })

assert len(rows) == 163, f"Expected 163 rows, got {len(rows)}"

def py_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

lines = [
    "# AUTO-GENERATED by scratch/generate_schema_py.py — do not edit by hand.",
    "# Source of truth: schema.tsv",
    "",
    "SCHEMA_DATA = [",
]

for r in rows:
    lines.append(
        f'    {{"id": {py_str(r["id"])}, "category": {py_str(r["category"])}, '
        f'"description": {py_str(r["description"])}, "parameter": {py_str(r["parameter"])}, '
        f'"content_type": {py_str(r["content_type"])}, "min": {py_str(r["min"])}, '
        f'"max": {py_str(r["max"])}, "ac": {py_str(r["ac"])}}},'
    )

lines += [
    "]",
    "",
    "# Flat list of parameter names — used by research & consolidation nodes",
    "PARAMETER_KEYS = [item['parameter'] for item in SCHEMA_DATA]",
    "",
    "# Validation rules derived from schema",
    "VALIDATION_RULES = {}",
    "for item in SCHEMA_DATA:",
    "    param = item['parameter']",
    "    rules = {",
    "        'required': True,",
    "        'type': item['content_type'],",
    "        'is_composite': item['ac'].lower() == 'composite',",
    "    }",
    "    if rules['is_composite']:",
    "        rules['min_elements'] = int(item['min']) if item['min'].isdigit() else 1",
    "        rules['max_elements'] = int(item['max']) if item['max'].isdigit() else 100",
    "    VALIDATION_RULES[param] = rules",
    "",
]

with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Written {len(rows)} parameters to {OUT_PATH}")
